### ISSUE TITLE
Unable to invite bot, "Could not deserialize events"

### ISSUE THREAD

**Issue by sot-tech** [exul/matrix-rocketchat#81]
When trying to invide bot, it does not accept invitation and bridge shows error:
`Could not deserialize events that were sent to the transactions endpoint`
see [rocketchat.log](https://github.com/exul/matrix-rocketchat/files/4959675/rocketchat.log)

Test configuration:
```yaml
hs_token: "VERYveryLONGsecureRANDOMstringBLAblaBLA"
as_token: "anotherVERYveryLONGsecureRANDOMstringBLAblaBLA"
as_address: "0.0.0.0:8081"
as_url: "http://MAGNESIUM.TEST.LOCAL:8081"
hs_url: "http://NATRIUM.TEST.LOCAL:8008"
hs_domain: "test.local"
sender_localpart: "rc_bot"
database_url: "./db/mrc.sqlite3"
log_level: "debug"
log_to_console: true
log_to_file: true
log_file_path: "/var/log/matrix/rocketchat.log"
accept_remote_invites: false
use_https: false
pkcs12_path: ""
pkcs12_password: ""

#### REGISTRATION ####
id: rc_as
namespaces:
    users:
    - exclusive: true
      regex: '@rcu_.+:test.local'
    aliases:
    - exclusive: true
      regex: '#rcg_.+:test.local'
url: http://MAGNESIUM.TEST.LOCAL:8081
sender_localpart: rc_bot
rate_limited: false
```
Homeserver: synapse 1.17.0-r0
